### ISSUE TITLE
Mac OS X workarounds

### ISSUE THREAD

**Issue by ptommasi** [hkbakke/bash-insulter#10]
Maybe it will be helpful to others, making it work on Mac OS needs a couple of tweaks!

The issues:
- date (line 69) doesn't format nano seconds properly (%N is not available under macos)
- shuf (line 74) doesn't exists either
- for some odd reason the variable RANDOM gives unexpected results (maybe it's a oh-my-zsh issue)
- error is printed twice (again, could be a oh-my-zsh issue)

The solution:
- I used brew, so let's first install coreutils (`brew install coreutils`), that will make gdate and gshuf available
- Replace `date` with `gdate` (line 69) and `shuf` with `gshuf` (line 74)
- Rename `RANDOM` into `RANDO` (or whatever)
- Comment the `echo` on line 105 to avoid double error printing under zsh

Attached the file with my modification, hope it helps! :)

[bash.command-not-found.txt](https://github.com/hkbakke/bash-insulter/files/1491204/bash.command-not-found.txt)

**Comment by hkbakke** [comment]
I don't own a mac but I have some comments:
RANDOM is not a variable, but a bash/zsh builtin random generator. RANDOM is seeded by giving it a value. Without the RANDOM functionality you will get the insult every time you type an invalid command.
I am guessing that oh-my-zsh does not have RANDOM builtin.

The issue I find the strangest is that you had to remove line 105 because the message was printed twice. If you get to that point in code it _should_ mean that you only print the insult and the error message. I am thinking that there must be something else outside the command_not_found_handler that prints the message, but I can't really check it as I do not have Mac OS.

**Comment by ptommasi** [comment]
Oh... that is my bad, there was even a comment: _Only print the insults some of the time_! I wasn't aware of the `RANDOM` builtin and I thought it was related with picking  element from the list, and then `shuf` to shuffle even further... My apologies, I feel like in a RTFM situation, `RANDOM` is working as expected! ^^

About the commented `echo`, I don't really know what's happening in the underlying level! Maybe the mac os bash / zsh has a different way to handle the handler! ¯\_(ツ)_/¯

**Comment by hkbakke** [comment]
No problem! I happily accept ideas or pull requests that makes the script compatible with Mac OS though, so just update if you find out something new.

**Comment by ptommasi** [comment]
I created a pull request for the shuf/date issue, I won't change the zsh behaviour since it may be my machine (I'll keep it just locally).

I may have issued two pull requests, the first was using an outdated version of your code (please ignore it), the second is the correct one (it uses the latest version of your code, easier to merge).

**Comment by hkbakke** [comment]
Your changes looks reasonable and your PR was merged.
